name: CI/CD Workflow

on:
  push:
    branches:
      - feature/villegas  # Esto indica que el flujo de trabajo se ejecuta cuando haces un push a feature/villegas
      - main               # También lo puedes activar en la rama main (si es necesario)
  pull_request:
    branches:
      - feature/villegas  # También se ejecuta cuando se hace un pull request hacia esta rama

jobs:
  # Primer trabajo: Validación de HTML
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Validar HTML
        uses: Cyb3r-Jak3/html5validator-action@v1.1.0
        with:
          file: index.html  # Asegúrate de que este archivo exista y esté en la raíz

  # Segundo trabajo: Despliegue con GitHub Pages (si lo deseas)
  deploy:
    runs-on: ubuntu-latest
    needs: validate-html  # Esto asegura que la validación HTML debe pasar antes de desplegar
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Setup Node.js (si es necesario para tu app)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # O la versión que necesites

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/v1.0.0  # Aquí va la carpeta que quieres desplegar
