name: CI - Validación HTML

on:
  push:
    branches:
      - main
      - feature/villegas
  pull_request:
    branches:
      - main
      - feature/villegas

jobs:
  html-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar html-validator-cli
        run: npm install -g html-validator-cli

      - name: Validar HTML en release/v2.0.0
        run: |
          html-validator --file release/v2.0.0/index.html --format text || true
