name: CI General

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

jobs:
  markdown-check:
    name: 📝 Verificar Markdown y enlaces
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar markdownlint-cli y markdown-link-check
        run: |
          npm install -g markdownlint-cli markdown-link-check

      - name: Lint de archivos Markdown
        run: markdownlint "**/*.md" || true  # Se agrega '|| true' para que el flujo continúe incluso si markdownlint falla

      - name: Verificar enlaces en Markdown
        run: |
          find . -type f -name "*.md" -exec markdown-link-check -q {} \; || true  # Evitar que falle el flujo si hay errores en enlaces

